language: python
env:
# - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.4.3
python:
  - "2.7"
install:
# - "pip install . --use-mirrors"
  - "pip install -q Django==$DJANGO_VERSION --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
  - "python setup.py -q install --use-mirrors"
# command to run tests
script: nosetests
